#!/usr/bin/env bash
# Render the runtime env file for an environment by merging, in order of
# increasing precedence:
#
#   1. env/common.env.example      (shared non-secret defaults)
#   2. env/<env>.env.example       (env-specific non-secret config)
#   3. versions/<env>.env          (pinned image tags)
#   4. AWS SSM Parameter Store      (/xental/<env>/* SecureString secrets)
#
# Output: env/<env>.runtime.env (chmod 600, git-ignored). docker compose then
# consumes it via --env-file. Later layers win because --env-file keeps the
# last definition of a duplicated key.
#
# Usage:  scripts/render-env.sh <staging|production>
#         SKIP_SSM=1 scripts/render-env.sh staging   # offline (no secrets)
set -euo pipefail

ENV_NAME="${1:?usage: render-env.sh <staging|production>}"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AWS_REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-eu-west-1}}"

common="$REPO_DIR/env/common.env.example"
envfile="$REPO_DIR/env/${ENV_NAME}.env.example"
versions="$REPO_DIR/versions/${ENV_NAME}.env"
out="$REPO_DIR/env/${ENV_NAME}.runtime.env"

for f in "$common" "$envfile" "$versions"; do
  [[ -f "$f" ]] || { echo "ERROR: missing $f" >&2; exit 1; }
done

# Keep only KEY=VALUE lines (drop comments/blanks) from the non-secret layers.
keep_kv() { grep -E '^[A-Za-z_][A-Za-z0-9_]*=' "$1" || true; }

umask 077
{
  echo "# AUTO-GENERATED by render-env.sh for ${ENV_NAME} — do not edit or commit."
  keep_kv "$common"
  keep_kv "$envfile"
  keep_kv "$versions"

  if [[ "${SKIP_SSM:-0}" != "1" ]]; then
    # Pull every SecureString under /xental/<env>/ and emit NAME=VALUE,
    # where NAME is the final path segment (e.g. POSTGRES_PASSWORD).
    aws ssm get-parameters-by-path \
      --path "/xental/${ENV_NAME}" \
      --with-decryption --recursive \
      --region "$AWS_REGION" \
      --query 'Parameters[].[Name,Value]' --output text \
    | while IFS=$'\t' read -r name value; do
        [[ -n "$name" ]] || continue
        printf '%s=%s\n' "${name##*/}" "$value"
      done
  else
    echo "# SKIP_SSM=1: secrets omitted (offline render)" >&2
  fi
} > "$out"

chmod 600 "$out"
echo "Rendered $out"
